import type {Metadata} from 'next';
import './globals.css';
import { Toaster } from "@/components/ui/toaster"
import { ThemeProvider } from "@/components/theme-provider"

export const metadata: Metadata = {
  title: 'Portfolio Maestro',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth" data-theme="dark" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700;900&display=swap" rel="stylesheet" />
        {/* No-flash theme init: default to dark, override with stored preference */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(()=>{try{const ls=localStorage.getItem('theme');const theme=(ls==='light'||ls==='dark')?ls:'dark';const root=document.documentElement;if(theme==='dark'){root.classList.add('dark')}else{root.classList.remove('dark')}root.setAttribute('data-theme',theme)}catch(e){}})();`,
          }}
        />
      </head>
      <body className="font-body antialiased">
        <ThemeProvider>
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
